# Generated by Django 3.1.5 on 2021-06-01 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('desc', models.TextField(blank=True, null=True)),
                ('sorted_by', models.IntegerField(default=1, unique=True, verbose_name='排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('developing', '开发中'), ('operating', '维护中'), ('stable', '稳定运行')], default='stable', max_length=32, verbose_name='项目状态')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
                ('version', models.CharField(default='v1.0', max_length=32, verbose_name='版本')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='项目管理员')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_update_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '项目表',
                'ordering': ['-sorted_by'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('desc', models.TextField(blank=True, null=True)),
                ('sorted_by', models.IntegerField(default=1, unique=True, verbose_name='排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='模块名称')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.project', verbose_name='所属项目')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_update_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '模块表',
                'ordering': ['-sorted_by'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('desc', models.TextField(blank=True, null=True)),
                ('sorted_by', models.IntegerField(default=1, unique=True, verbose_name='排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='ip地址')),
                ('port', models.SmallIntegerField(default=80, verbose_name='端口号')),
                ('category', models.SmallIntegerField(choices=[(0, 'web服务器'), (1, '数据库服务器')], default=0, verbose_name='服务器类型')),
                ('os', models.SmallIntegerField(choices=[(0, 'windows'), (1, 'linux')], default=0, verbose_name='操作系统')),
                ('status', models.SmallIntegerField(choices=[(0, 'active'), (1, 'disable')], default=0, verbose_name='服务器状态')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.project', verbose_name='所属项目')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_update_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '测试环境表',
                'ordering': ['-sorted_by'],
                'abstract': False,
            },
        ),
    ]
