# Generated by Django 3.1.5 on 2021-06-02 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tp', '0003_auto_20210602_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('desc', models.TextField(blank=True, null=True)),
                ('sorted_by', models.IntegerField(default=1, unique=True, verbose_name='排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='触发时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('case_num', models.SmallIntegerField(default=0, verbose_name='用例数')),
                ('pass_num', models.SmallIntegerField(default=0, verbose_name='通过用例数')),
                ('failed_num', models.SmallIntegerField(default=0, verbose_name='失败用例数')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tp.plan', verbose_name='测试计划')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_update_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '测试结果',
                'ordering': ['-sorted_by'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Reault',
        ),
    ]
