# Generated by Django 3.1.5 on 2021-06-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0005_auto_20210602_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='httpapi',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='plancase',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='result',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='step',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sorted_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
