# Generated by Django 3.1.5 on 2021-06-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0008_auto_20210603_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['step_no'], 'verbose_name': '测试步骤表'},
        ),
        migrations.RenameField(
            model_name='step',
            old_name='setp_no',
            new_name='step_no',
        ),
    ]
