# Generated by Django 3.1.5 on 2021-06-08 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tp', '0010_auto_20210608_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='result',
            name='failed_num',
            field=models.SmallIntegerField(default=0, verbose_name='失败数'),
        ),
        migrations.AlterField(
            model_name='result',
            name='pass_num',
            field=models.SmallIntegerField(default=0, verbose_name='通过数'),
        ),
    ]
