# Generated by Django 3.1.5 on 2021-06-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tp', '0011_auto_20210608_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='项目组'),
        ),
    ]
