# Generated by Django 3.1.5 on 2021-06-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0016_auto_20210616_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='environment',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='httpapi',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='plancase',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_time',
            new_name='create_time',
        ),
    ]
